hmcts/template-expressjs

cookiecutter.json, {{cookiecutter.component_id}}/component-info.yaml
=> add component info

{{cookiecutter.component_id}}/README.md
=> Fix heading in read me

{{cookiecutter.component_id}}/.gitignore, {{cookiecutter.component_id}}/package.json, {{cookiecutter.component_id}}/src/main/development.ts, {{cookiecutter.component_id}}/src/main/views/webpack/css-template.njk, {{cookiecutter.component_id}}/src/main/views/webpack/css.njk, {{cookiecutter.component_id}}/src/main/views/webpack/js-template.njk, {{cookiecutter.component_id}}/src/main/views/webpack/js.njk, {{cookiecutter.component_id}}/webpack.config.js, {{cookiecutter.component_id}}/webpack/htmlWebpack.js, {{cookiecutter.component_id}}/webpack/scss.js, {{cookiecutter.component_id}}/yarn.lock
Taking fix from https://github.com/hmcts/incident-response-frontend
```
[ ] Yes
[x] No
```
=> Fix web pack

.dependabot/config.yml, {{cookiecutter.component_id}}/.dependabot/config.yml
=> Add dependabot config

{{cookiecutter.component_id}}/charts/{{ cookiecutter.app_full_name }}/values.preview.template.yaml
Change in line with original template
```
[ ] Yes
[ x] No
```
=> remove empty environment: from preview

.github/renovate.json, .github/workflows/checks.yml
=> Add dependencies labels to renovate PRs

cookiecutter.json, {{cookiecutter.component_id}}/catalog-info.yaml
=> Add annotations and tags

skeleton/src/main/views/error.njk, skeleton/src/main/views/home.njk, skeleton/src/main/views/template.njk, template.yaml
**Before creating a pull request make sure that:**
Please remove this line and everything above and fill the following sections:
```
[ ] Yes
[ ] No
```
=> DTSPO-5580 Remove end chomp

skeleton/src/main/views/not-found.njk
**Before creating a pull request make sure that:**
Please remove this line and everything above and fill the following sections:
```
[ ] Yes
[ ] No
```
=> DTSPO-5580 One template missing raw

skeleton/src/main/views/error.njk, skeleton/src/main/views/home.njk, skeleton/src/main/views/macros/csrf.njk, skeleton/src/main/views/not-found.njk, skeleton/src/main/views/template.njk
**Before creating a pull request make sure that:**
Please remove this line and everything above and fill the following sections:
```
[ ] Yes
[ ] No
```
=> DTSPO-5580 Fix CSRF macro

skeleton/charts/${{ values.app_full_name }}/values.yaml
DTSPO-5507
Changed ingress host formatting
```
[ ] Yes
[X] No
```
=> DTSPO-5507 - change ingress host formatting

skeleton/yarn.lock
DTSPO-5507
File yarn.lock updated using `yarn install` command
```
[ ] Yes
[X] No
```
=> DTSPO-5507 - yarn lock file updated

skeleton/src/main/modules/appinsights/index.ts
DTSPO-5507
Linting fixed
```
[ ] Yes
[X] No
```
=> linting fixed

skeleton/jest.smoke.config.js, skeleton/package.json, skeleton/src/main/modules/appinsights/index.ts, skeleton/yarn.lock
DTSPO-5507 
jest-junit added to template, yarn linting error fixed
```
[ ] Yes
[X] No
```
=> DTSPO-5507 - jest-junit added to template, yarn linting error fixed

template.yaml
**Before creating a pull request make sure that:**
Please remove this line and everything above and fill the following sections:
```
[ ] Yes
[ ] No
```
=> Add Github Topics

template.yaml
Based on docs at https://backstage.platform.hmcts.net/create/actions
=> Hopefully fix backstage templating

skeleton/Jenkinsfile_CNP
It doesn't work right with zero-installs so needs rebuilding
=> DTSPO-6464 Rebuild puppeteer on pipeline

.github/renovate.json
Trying this to speed up auto merges
```
[ ] Yes
[x] No
```
=> DTSPO-11734 - renovate - enable platformAutomerge

.github/renovate.json
add schema to renovate file
```
[ ] Yes
[x] No
```
=> DTSPO-11734 - renovate - add schema

.github/CODEOWNERS
Adding files and paths updated by renovate so code owner approval is not needed
```
[ ] Yes
[x] No
```
=> Ignore files and paths updated by renovate
